// Note: The wasm pkg will be generated by wasm-pack
import init, { VanityEngine } from '../../../engine/pkg/vanity_engine';

let engine: VanityEngine | null = null;
let isInitialized = false;

// Convert hex string to byte array
function parseHexPattern(hexStr: string): Uint8Array {
  let cleanStr = hexStr.toLowerCase().replace(/^0x/, '');
  if (cleanStr.length % 2 !== 0) {
    cleanStr += '0'; // Pad to even length
  }
  
  const byteLen = cleanStr.length / 2;
  const bytes = new Uint8Array(byteLen);
  
  for (let i = 0; i < byteLen; i++) {
    bytes[i] = parseInt(cleanStr.substring(i * 2, i * 2 + 2), 16);
  }
  
  return bytes;
}

self.onmessage = async (e: MessageEvent) => {
  const { type, payload } = e.data;

  if (type === 'INIT') {
    try {
      await init();
      engine = new VanityEngine();
      isInitialized = true;
      self.postMessage({ type: 'INIT_DONE' });
    } catch (err) {
      self.postMessage({ type: 'ERROR', error: String(err) });
    }
  } else if (type === 'START') {
    if (!isInitialized || !engine) {
      self.postMessage({ type: 'ERROR', error: 'Worker not initialized' });
      return;
    }

    const { prefix, suffix, sharedBuffer, batchSize = 1000 } = payload;
    const flagArray = new Uint8Array(sharedBuffer);
    
    // Parse to byte arrays once outside the loop
    const prefixBytes = parseHexPattern(prefix || '');
    const suffixBytes = parseHexPattern(suffix || '');

    let attempts = 0;
    
    try {
      // Tight generation loop
      while (Atomics.load(flagArray, 0) === 0) {
        const result = engine.search_batch(
          prefixBytes,
          suffixBytes,
          batchSize
        );

        attempts += batchSize;

        if (result) {
          if (Atomics.compareExchange(flagArray, 0, 0, 1) === 0) {
            self.postMessage({
              type: 'FOUND',
              result: {
                address: result.address,
                privateKey: result.private_key
              },
              attempts
            });
          }
          break;
        }

        if (attempts >= 50000) {
          self.postMessage({ type: 'PROGRESS', attempts });
          attempts = 0;
        }
      }
      
      if (attempts > 0 && Atomics.load(flagArray, 0) !== 0) {
         self.postMessage({ type: 'PROGRESS', attempts });
      }

      self.postMessage({ type: 'STOPPED' });
    } catch (err) {
      self.postMessage({ type: 'ERROR', error: String(err) });
    }
  }
};
