// Note: The wasm pkg will be generated by wasm-pack
import init, { VanityEngine } from '../../../engine/pkg/vanity_engine';

let engine: VanityEngine | null = null;
let isInitialized = false;

self.onmessage = async (e: MessageEvent) => {
  const { type, payload } = e.data;

  if (type === 'INIT') {
    try {
      await init();
      engine = new VanityEngine();
      isInitialized = true;
      self.postMessage({ type: 'INIT_DONE' });
    } catch (err) {
      self.postMessage({ type: 'ERROR', error: String(err) });
    }
  } else if (type === 'START') {
    if (!isInitialized || !engine) {
      self.postMessage({ type: 'ERROR', error: 'Worker not initialized' });
      return;
    }

    const { prefix, suffix, sharedBuffer, batchSize = 5000 } = payload;
    const flagArray = new Uint8Array(sharedBuffer);

    let attempts = 0;
    
    try {
      // Tight generation loop
      while (Atomics.load(flagArray, 0) === 0) {
        const result = engine.search_batch(
          prefix || '',
          suffix || '',
          batchSize
        );

        attempts += batchSize;

        if (result) {
          // Double check flag in case another worker found it exactly at the same time
          if (Atomics.compareExchange(flagArray, 0, 0, 1) === 0) {
            self.postMessage({
              type: 'FOUND',
              result: {
                address: result.address,
                privateKey: result.private_key
              },
              attempts
            });
          }
          break;
        }

        // Report progress every 50k attempts to avoid flooding the message queue
        if (attempts >= 50000) {
          self.postMessage({ type: 'PROGRESS', attempts });
          attempts = 0;
        }
      }
      
      // If we exit loop and have remaining attempts to report
      if (attempts > 0 && Atomics.load(flagArray, 0) !== 0) {
         self.postMessage({ type: 'PROGRESS', attempts });
      }

      self.postMessage({ type: 'STOPPED' });
    } catch (err) {
      self.postMessage({ type: 'ERROR', error: String(err) });
    }
  }
};
